16 create components
WildCodeSchool/lille-js-202003-project-jubilant-narwhal-frontend pull request #3
Opened 2020-06-17 08:32 UTC by snefrou2

create all components for the agenda

2020-06-17 09:42 UTC, magb7 submitted a review, later dismissed
See No Evil

2020-06-17 18:05 UTC, LoicBrassart requested changes
- AddNewHomework is styled using `rn-css` while Checkbox uses `react-native`. Why use two distinct libraries for styling ?
- Where are my `;` ?
- ViewRightButton has no indentation rule
- DayColumn uses `rgb()` and `#` notations for colors: please choose one and stick to it for the whole project

2020-06-17 18:05 UTC, LoicBrassart commented on src/components/AddNewHomework.tsx
> +
Two consecutive whitespaces ? Shouldn't Prettier get rid of that ? :thinking:

2020-06-17 18:05 UTC, LoicBrassart commented on src/components/Button/LeftArrow.tsx
> +        console.log('fleche')
It makes me grunt to let this pass, even though I know why >_<

2020-06-17 18:05 UTC, LoicBrassart commented on src/components/TaskDoneOverlay.tsx
> +        style={{ width: '150px', height: '150px' }}
Why use inline styles just there ?

2020-06-19 14:23 UTC, magb7 commented on src/components/Button/LeftArrow.tsx
> +        console.log('fleche')
With Native, we can't write a onPress without a something in the function :/

2020-06-19 14:27 UTC, magb7 commented on src/components/TaskDoneOverlay.tsx
> +        style={{ width: '150px', height: '150px' }}
Maybe because I was tired :)

2020-06-19 14:50 UTC, magb7 commented on src/components/AddNewHomework.tsx
> +
There are no TWO consecutive whitespaces ! 
If you take a closer look, you can see that there is a backstick line 7 ! 

But I can understand you missed it, it's small.

2020-06-22 09:06 UTC, magb7 approved these changes
Everything's fine !  We add a README file with information on rn-css in it.

2020-06-22 14:47 UTC, LoicBrassart approved these changes
Saw no Evil

2020-06-22 14:49 UTC, merged